# This is a basic workflow to help you get started with Actions

name: LibClang tutorial

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Change the runner to macOS
    runs-on: macos-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies using Homebrew
      - name: Install dependencies
        run: |
          brew update
          brew install git coreutils

      - name: Debug Check installed tools
        run: |
          echo "Check coreutils installation:"
          which dirname
          which readlink
          echo "Current PATH:"
          echo $PATH

      # Install LLVM using Homebrew
      - name: Install LLVM
        run: |
          brew install llvm@15
          LLVM_PREFIX=$(brew --prefix llvm@15)
          echo "LLVM_PREFIX=$LLVM_PREFIX" >> $GITHUB_ENV
          echo "PATH=$LLVM_PREFIX/bin:$PATH" >> $GITHUB_ENV
          echo "LDFLAGS=-L$LLVM_PREFIX/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$LLVM_PREFIX/include" >> $GITHUB_ENV

      - name: Verify LLVM Installation
        run: |
          source $GITHUB_ENV
          llvm-config --version

      - name: Configure Project
        run: |
          source $GITHUB_ENV
          cmake .

      - name: Build Project
        run: |
          source $GITHUB_ENV
          make VERBOSE=1

      - name: List All Files in Repository
        run: |
          find $GITHUB_WORKSPACE -type f -exec ls -lh {} \;

      # Upload the hello-world binary as an artifact
      - name: Upload hello-world binary
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-binary
          path: ${{ github.workspace }}/bin/hello-world # path to the binary
